---
title: "Data transformation"
subtitle: "`dplyr`"
author: "Roland Krause"
date: "2021-11-07"
---


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

### Judgment
This short tutorial will allow you to explore `dplyr` functionality based on the previous lecture. Every question can be answered with a combination of `%>%` pipes. You should refrain from using temporary variables and statements outside of the range of the tidyverse.  

##### Import the [data from the website](  https://biostat2.uni.lu/practicals/data/judgments.tsv). 
Assign to the name `judgments`


##### Use `glimpse()` to identify columns and column types.

##### Select all columns that refer to the STAI questionnaire


##### Select all subjects older than 25


##### Retrieve all subjects younger than 20 which are in the stress group
The column for the group is `condition`.


##### Abbreviate the gender column such that only the first character remains


##### Normalize the values in the REI group
Divide all entries in the REI questionnaire by 5, the maximal value.

##### Compute the average and the standard deviation for all moral dilemma columns. 
The resulting column names must contain the names of "avg" (for the average) and "sd"
for the standard deviation. 


